# Generated by Django 5.0.6 on 2024-06-16 05:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChaiVariety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='chais/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('chai_type', models.CharField(choices=[('DW', 'Doodh wali'), ('KT', 'Katak chai'), ('KW', 'Kawa'), ('GT', 'Green Tea'), ('EL', 'Elachi wali')], max_length=2)),
            ],
        ),
    ]
