# Generated by Django 5.0.6 on 2024-06-19 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0003_chaicertificate_chaireview_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chaivariety',
            old_name='chai_type',
            new_name='type',
        ),
    ]
